name: Python Quality Check

on: [push, pull_request] # Se activa cada vez que subes a GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pylint pytest
    - name: Analysing the code with pylint
      run: |
        pylint src/
    - name: Test with pytest
      run: |
        pytest